image: docker:stable

stages:
  - build

variables:
  EXTRA_FLAGS: ""
  STATS_LEVEL: 0
  CLICKOS_BR: persistent-grants
  CLICKOS_REPO: https://github.com/willfantom/clickos
  MINIOS_BR: master
  MINIOS_REPO: https://github.com/sysml/mini-os
  TOOLCHAIN_BR: master
  TOOLCHAIN_REPO: https://github.com/sysml/toolchain
  XEN_BR: stable-4.11
  XEN_REPO: https://github.com/xen-project/xen
  DOCKER_IMG: ${DOCKER_REGISTRY}/${DOCKER_REGISTRY_USER}/${PROJECT}

before_script:
  - docker login --username ${DOCKER_REGISTRY_USER} --password ${DOCKER_REGISTRY_PASSWORD} ${DOCKER_REGISTRY}

build:
  stage: build
  services:
  - name: docker:stable-dind
  script:
    - "docker build -f Dockerfile --rm --compress --no-cache \
        --build-arg EXTRA_FLAGS=${EXTRA_FLAGS} --build-arg STATS_LEVEL=${STATS_LEVEL} \
        --build-arg CLICKOS_BR=${CLICKOS_BR} --build-arg CLICKOS_REPO=${CLICKOS_REPO} \
        --build-arg MINIOS_BR=${MINIOS_BR} --build-arg MINIOS_REPO=${MINIOS_REPO} \
        --build-arg TOOLCHAIN_BR=${TOOLCHAIN_BR} --build-arg TOOLCHAIN_REPO=${TOOLCHAIN_REPO} \
        --build-arg XEN_BR=${XEN_BR} --build-arg XEN_REPO=${XEN_REPO} \
        --tag ${DOCKER_IMG}:${TAG} ."
    - docker push ${DOCKER_IMG}:${TAG}
