name: Upload Docker Images

on: [push, workflow_dispatch]

jobs:
  build-docker:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Extract Repo Owner
        shell: bash
        run: echo "##[set-output name=owner;]$(echo ${GITHUB_REPOSITORY%%/*} | tr '[:upper:]' '[:lower:]')"
        id: extract_owner
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: GHCR Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ steps.extract_owner.outputs.owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and Push Environment
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.environment
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ steps.extract_owner.outputs.owner }}/clickos:environment
          no-cache: true
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
      -
        name: Build and Push Sysml
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            CLICKOS_BR=persistent-grants
          tags: |
            ghcr.io/${{ steps.extract_owner.outputs.owner }}/clickos:sysml
          no-cache: true
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
      -
        name: Build and Push Dev Environment
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.dev
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ steps.extract_owner.outputs.owner }}/clickos:development
          no-cache: true
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
