name: Upload Docker Images

on: [push, workflow_dispatch]

jobs:
  build-docker:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Extract Repo Owner
        shell: bash
        run: echo "##[set-output name=owner;]$(echo ${GITHUB_REPOSITORY%%/*} | tr '[:upper:]' '[:lower:]')"
        id: extract_owner
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: DockerHub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: GHCR Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ steps.extract_owner.outputs.owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ steps.extract_owner.outputs.owner }}/clickos:sysml
            docker.io/${{ secrets.DOCKER_USERNAME }}/clickos:sysml
          no-cache: true
      -
        name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.dev
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ steps.extract_owner.outputs.owner }}/clickos:development
            docker.io/${{ secrets.DOCKER_USERNAME }}/clickos:development
          no-cache: true
